[package]
name = "simple_conv"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
syact = { path = "../../" } # "0.12.0"          # Importing the library

[features]
rasp = [ "syact/rasp" ]   # Creating the platform feature for our raspberry pi
direct = [ ]
predef = [ ]