[package]
name = "simple_conv"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
stepper_lib = { path = "../../" } # "0.11.6"          # Importing the library

[features]
rasp = [ "stepper_lib/rasp" ]   # Creating the platform feature for our raspberry pi
direct = [ ]
predef = [ ]